### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by fungoza** [enjarai/client-paintings#1]
GIF paintings supported?

**Comment by enjarai** [comment]
I actually haven't thought of this, but it's definitely a good idea. In fact, it *might* already be supported if you use a vanilla animated texture with an mcmeta file. I haven't tested that though.

**Comment by UIONUION-ux** [comment]
What should be the PNG format if, for example, I want a 2 by 2 image?

**Comment by enjarai** [comment]
> What should be the PNG format if, for example, I want a 2 by 2 image?

This does not seem very relevant to this issue. Please dont hijack an issue to ask your question, instead, either make a new one or contact me on my discord guild.

**Comment by UIONUION-ux** [comment]
ok thanks for the reply

**Comment by enjarai** [comment]
I can confirm that animated paintings do in fact work out of the box. You just add an mcmeta file to your texture, similar to vanilla.

https://github.com/enjarai/client-paintings/assets/38552516/d2122a9e-bce1-40e0-984e-9dac341901c9

A default example has been added to the builtin resource pack as of 1.2.0.
