### ISSUE TITLE
Client Paintings doesn't work when default paintings are larger than base size

### ISSUE THREAD

**Issue by Aqre** [enjarai/client-paintings#2]
When I change Minecraft's default paintings to a size larger than it's base size, client paintings will fail to replace those paintings. 
Example:
Default painting size:
![image](https://github.com/enjarai/client-paintings/assets/51094192/b8e5fadf-2a5b-437a-aea8-22ba21c15a15)

Large painting size:
![image](https://github.com/enjarai/client-paintings/assets/51094192/d495f90b-2704-4ad0-8eff-2cd96fd55809)

**Comment by enjarai** [comment]
Found the issue, I'll push out an update soon.

**Comment by enjarai** [comment]
Fixed in 1.2.0.
