### ISSUE TITLE
Release 1.0.0 needs separate file to support 1.19

### ISSUE THREAD

**Issue by Geird** [enjarai/client-paintings#3]
1.19.2 changed the mod id of Fabric from _fabric_ to _fabric-api_, preventing this mod from working on 1.19. 
Adjusting the depends section of the fabric.mod.json to the below fixes the problem.

> depends": {
>     "minecraft": ">=1.19 <1.19.3-",
>     "fabric": "*"
>   }

**Comment by enjarai** [comment]
Wow, I didn't know anyone was actually using this mod lmao. I've fixed the issue and pushed a new release that coincidentally backports some small newer features I added post-1.19.4.
